import './globals.css'
import { Poppins, Unbounded } from 'next/font/google'
import AppShell from '@/components/layout/AppShell'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-secondary'
})

const unbounded = Unbounded({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-primary'
})

export const metadata = {
  title: 'Internet of Things',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${unbounded.variable}`}>
      <body className='bg-background text-white font-secondary'>
        <AppShell>
         {children}
        </AppShell>
      </body>
    </html>
  )
}
